const state = {
  characters:[{id:'duran',name:'Duran',className:'Warlock',level:5,hp:34,maxHp:38,ac:15,conditions:[],resources:{spellSlots:2},abilities:['Eldritch Blast'],inventory:['Arcane focus']},{id:'bonnie',name:'Bonnie',className:'Bard',level:5,hp:31,maxHp:35,ac:14,conditions:[],resources:{bardicInspiration:4},abilities:['Bardic Inspiration'],inventory:['Lute']},{id:'trent',name:'Trent',className:'Fighter',level:5,hp:44,maxHp:48,ac:18,conditions:[],resources:{secondWind:1},abilities:['Action Surge'],inventory:['Grappling hook']}],
  cards:[{id:'srd-grapple',title:'Grappled (SRD)',type:'Rule',body:'A grappled creature has speed 0. The condition ends if the grappler is incapacitated or an effect removes the creature from reach.',visibility:['dm']},{id:'npc-mira',title:'Mira Vell',type:'NPC',body:'Moon-cult archivist with private campaign notes. User-authored homebrew slot.',visibility:['dm']},{id:'spell-eb',title:'Eldritch Blast (SRD reference)',type:'Spell',body:'A ranged spell attack can create more beams at higher levels. Keep proprietary text out; add private notes manually.',visibility:['dm']}],
  tvCards:[],log:['Session started in local-first mode.'],initiative:['Duran','Bonnie','Trent'],tokens:[{id:'tok-duran',name:'Duran',x:1,y:1,hp:34,maxHp:38,status:[],kind:'pc'},{id:'tok-goblin',name:'Goblin',x:5,y:4,hp:7,maxHp:7,status:[],kind:'monster'}],proposals:[]
};
function createProposal(prompt){const p=String(prompt).toLowerCase();const id=`proposal-${Date.now()}`;const base={id,createdAt:new Date().toISOString(),prompt,status:'pending'};if(p.includes('duran')||p.includes('eldritch'))return{...base,kind:'character-update',summary:'Add an approved homebrew Eldritch Blast beam enhancer to Duran.',target:'duran',patch:{abilitiesAdd:['Homebrew: Eldritch Barrage (+4 beams)']}};if(p.includes('bonnie')||p.includes('magic item'))return{...base,kind:'item',summary:'Create a bardic inspiration reward item for Bonnie.',target:'bonnie',patch:{inventoryAdd:['Homebrew: Harmonic Muse Charm']}};if(p.includes('frightened')||p.includes('goblin'))return{...base,kind:'condition',summary:'Apply frightened to all goblin tokens for 1 round.',target:'battlemap',patch:{tokenNameIncludes:'goblin',statusAdd:'frightened (1 round)'}};if(p.includes('image')||p.includes('scene'))return{...base,kind:'scene',summary:'Draft a cinematic image prompt for the TV display.',target:'tv',patch:{card:{title:'Ruined Moon Cathedral Prompt',type:'Scene Prompt',body:`Cinematic fantasy scene: ${prompt}`}}};return{...base,kind:'feat',summary:'Create a structured homebrew proposal for DM review.',target:'log',patch:{log:`Homebrew proposal: ${prompt}`}}}
function applyProposal(proposal){proposal.status='approved';const patch=proposal.patch;const c=state.characters.find(x=>x.id===proposal.target);if(c){if(patch.abilitiesAdd)c.abilities.push(...patch.abilitiesAdd);if(patch.inventoryAdd)c.inventory.push(...patch.inventoryAdd)}if(patch.statusAdd)state.tokens.filter(t=>t.name.toLowerCase().includes(String(patch.tokenNameIncludes))).forEach(t=>t.status.push(patch.statusAdd));if(patch.card){const card={id:`card-${Date.now()}`,visibility:['tv'],...patch.card};state.cards.push(card);state.tvCards.unshift(card)}if(patch.log)state.log.push(patch.log);state.log.push(`Approved: ${proposal.summary}`)}
function search(query){const q=String(query||'').toLowerCase();const pcCards=state.characters.map(c=>({id:c.id,title:c.name,type:'PC',body:`${c.className} ${c.level}, HP ${c.hp}/${c.maxHp}, AC ${c.ac}`,visibility:['dm']}));return[...state.cards,...pcCards].filter(x=>`${x.title} ${x.type} ${x.body}`.toLowerCase().includes(q))}
module.exports={state,createProposal,applyProposal,search};
